### ISSUE TITLE
Won't parse json.... arrays?

### ISSUE THREAD

**Issue by ianklatzco** [bahbka/pebble-my-data#2]
MyData won't parse an array of this form. Please note that I'm new to json and I haven't looked through the code/don't know if this is intended or not.

**Comment by ianklatzco** [comment]
{"content": ["username"], "theme": 0, "vibrate": 0, "updown": 1, "light": 0, "font": 4, "scroll": 33, "refresh": 300, "blink": 3}

**Comment by zagran** [comment]
your JSON valid, but in "content" exepted char 1024
#define CONTENT_SIZE 1024

try this
{"content": "username", "theme": 0, "vibrate": 0, "updown": 1, "light": 0, "font": 4, "scroll": 33, "refresh": 300, "blink": 3}

**Comment by ianklatzco** [comment]
I ended up fixing it by changing how my python script makes the JSON: "content": "username, username" (from a string, since it comes out as a python array ["username", "user2"], so I pass it to ", ".join(usernamearray)

**Comment by bahbka** [comment]
Sorry, missed this issue. Yes, My Data cannot parse arrays, because there are no single way to represent it and I want to keep my application simple. You must process this at server side.
