### ISSUE TITLE
What encoding to use for cyrillic text

### ISSUE THREAD

**Issue by peterkurishev** [bahbka/pebble-my-data#3]
Hello! I've tried to use uff-8 and windows-1251 encodings and in both cases the output can't be displayed correctly.

**Comment by bahbka** [comment]
UTF-8, but you need [custom firmware](http://pebblebits.com) with cyrillic font.

**Comment by peterkurishev** [comment]
Yes, I know this. And I tried both 2.9 beta7 and 2.8.1 pebblebits firmware...

The "screenshot" is attached. The last line is cyrillic "Тест" string supplied.
![img_1098](https://cloud.githubusercontent.com/assets/1374149/5998361/81376196-aad7-11e4-9d31-7cc6d1a6ddf7.jpg)

**Comment by bahbka** [comment]
Hmmm... Check your web server charset. Try [this url](https://bahbka.com/test) for testing. It works for me:
![img_20150202_124001 2](https://cloud.githubusercontent.com/assets/1660428/5998539/8b641dce-aad9-11e4-9c32-83ade01023f5.jpg)

**Comment by bahbka** [comment]
Please, reopen if problem still exists.
