### ISSUE TITLE
Append GPS coordinates to URL

### ISSUE THREAD

**Issue by zagran** [bahbka/pebble-my-data#4]
hi guys!
found some strange in GPS-feature (Append GPS coordinates to URL)
Pebble add coordinates, but coordinate relevance is 10 minutes. only after 10 min I see at server new coordinates. its my fault or it normal? may be it's impossible to change this duration by some parameter?

**Comment by bahbka** [comment]
Yes, there is GPS 10min cache for phone battery saving. I'll try to add it to configuration screen.
